name: Server Render Search

on:
  push:
    branches:    
      - master

jobs:
  build:
    name: My Send
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
        
    - name: 'Install NPM dependencies'
      run: 
        npm install axios jsdom 
        
    - name: Run Create local changes
      run: node index.js
      env:
        API: ${{ secrets.API }} 
        TOKEN: ${{ secrets.TOKEN }}   

    - name: Commit files
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: 'master'
    
